config/routes.rb
Rails.application.routes.draw do
  root to: "links#index"

  devise_for :users
  
  # resources :links, except: :show
  resources :links

  
  #Parse the real shortened URL
  get '/s/:ending', to: 'links#redirecting_screen', as: :redirex


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  has_many :visits
  has_many :visitors, through: :visits

  before_save :generate_ending
  validates :url, presence: true    
  validates :url, format: URI::regexp(%w[http https])
  validates_length_of :url, within: 3..511, on: :create, message: "too long"
  
   def generate_ending
     self.ending = SecureRandom.uuid[0..5] if self.ending.nil? || self.ending.empty?
     true
   end
  
   def short
     Rails.application.routes.url_helpers.redirex_url(ending: self.ending)
   end
  
   def self.shorten(url, ending = '')
  #   # return short when URL with that ending was created before
     link = Link.where(url: url, ending: ending, users_id: users_id).first
     return link.short if link 
        
  #   # create a new
     link = Link.new(url: url, ending: ending, users_id: users_id)
     return link.short if link.save
        
  #   # if ending is taken, try to add random characters
    Link.shorten(url, ending + SecureRandom.uuid[0..2])
  end
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
  #validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  
  has_many :links, dependent: :destroy



  

end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :link
  belongs_to :visitor
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  has_many :visits
  has_many :links, through: :visits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ] 



  # GET /links or /links.json
  def index
    @links = current_user.links.all
  end

  def redirecting_screen
   @link = Link.find_by_ending(params[:ending]) 
   render 'errors/404', status: 404 if @link.nil?
   @link.update_attribute(:counter, @link.counter + 1)
   # redirect_to @link.url
  end

  # GET /links/1 or /links/1.json
  def redirect_to_link
    @link = Link.find_by_ending(params[:ending]) 
    render 'errors/404', status: 404 if @link.nil?
    @link.update_attribute(:counter, @link.counter + 1)
    render @link
    # redirect_to @link.url
  end
  
  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = current_user.links.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:title, :url, :user_id)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController


end

app/helpers/application_helper.rb
module ApplicationHelper

    module BootstrapExtension
      FORM_CONTROL_CLASS = "form-control"
  
      # Override the 'text_field_tag' method defined in FormTagHelper[1]
      #
      # [1] https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_tag_helper.rb
      def text_field_tag(name, value = nil, options = {})
        class_name = options[:class]
        if class_name.nil?
          # Add 'form-control' as the only class if no class was provided
          options[:class] = FORM_CONTROL_CLASS
        else
          # Add ' form-control' to the class if it doesn't already exist
          options[:class] << " #{FORM_CONTROL_CLASS}" if
            " #{class_name} ".index(" #{FORM_CONTROL_CLASS} ").nil?
        end
  
        # Call the original 'text_field_tag' method to do the real work
        super
      end
    end
  
    # Add the modified method to ApplicationHelper
    include BootstrapExtension
  
  end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>KOMPAKTER</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/8591f4e3ea.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>


<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="/">KMPKTR</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/links">Links</a>
          </li>
        </ul>
        <p class="navbar-text float-right">
          <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </div>
    </div>
  </nav>

  <div class="container">

    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>
  <footer>
    <div class="container">
      TheMancodes <%= Time.now.year %>
    </div>
  </footer>
  
  
</body>

</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <%
=begin%>
 <div class="field">
    <%= form.label :ending %>
    <%= form.text_field :ending, class: 'form-control' %>
  </div> 
<%
=end%>


  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <%= form.text_field :users_id, id: :index_links_on_users_id, class: 'form-control', value: current_user.id %>


  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
  
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link, class: 'btn' %> |

<%= link_to 'Back', links_path, class: 'btn' %>

app/views/links/index.html.erb
<h1 class="display-4 mt-4 pb-4">KOMPAKTED LINKS</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Url</th>
      <th scope="col">Name</th>
      <th scope="col">Shortened url</th>
      <th colspan="1"></th>
      <th scope="col">Tally</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.title %></td>
        <td><%= link.url %></td>
        <td><a href="<%= link.short %>" target="_blank"><%= link.short %></a></td>
        <td><span class="fas fa-clipboard"></span></td>
        <td><%= link_to 'Edit', edit_link_path(link), class: 'btn' %></td>
        <td><%= link.counter %></td>
        <%
=begin%>
 <td><%= link_to 'redirect_to_link', link, class: 'btn' %></td> 
<%
=end%>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  <%= link_to 'New Link', new_link_path, class: 'btn btn-primary' %>

app/views/links/new.html.erb
<h1 class="display-4 mt-4">New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path, class: 'btn' %>

app/views/links/redirecting_screen.erb
<h1>You are being redirected</h1>
<span>If your are not redirected, </span><a href="<%= @link.url %>" target="_blank">click here <%= @link.url %></a>
<%= javascript_pack_tag 'redirecting_logic' %>
</br>

app/views/links/show.html.erb
<div>
  <h1>Congratulations! your short link is:</h1>
  <br>
  <a href="<%== @link.short %>" target="_blank"><%= @link.short %></a>
</div>


<%= link_to 'Edit', edit_link_path(@link), class: 'btn'  %> 
<%= link_to 'Back', links_path,  class: 'btn'  %>